### ISSUE TITLE
hint: The '.git/hooks/pre-commit' hook was ignored because it's not set as executable.

### ISSUE THREAD

**Issue by allanbowe** [peacechen/node-git-hooks#2]
Hi - great library, small and lightweight!

I have added a hook in `.githooks` and ran `npm install` and it appeared just fine in `.git/hooks/`.

The problem is, when running `git commit` I get this:
```
hint: The '.git/hooks/pre-commit' hook was ignored because it's not set as executable.
```
For sure I can just change the permissions, but that won't necessarily be performed by other developers (especially the ones that are likely to overlook the rules we are trying to enforce).

Is there a way for this action to be performed when running `npm i` ?

**Comment by allanbowe** [comment]
Actually - this was an easy fix.  I just needed to set the right permissions on the file in the `.githooks` directory first, then it was copied across just fine after running `npm install`.

**Comment by peacechen** [comment]
That's helpful information. I'll add it to the Readme.
